spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:carpathian}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

  # Configure Redis for caching hot queries and editorial lists.  If
  # Redis is not installed locally, leave these defaults and caching
  # will silently fall back to no‑op.
  redis:
    host: localhost
    port: 6379

  # Internationalization: define message bundles without locale suffix.
  messages:
    basename: messages

  # Configure task scheduling using the Europe/Kyiv time zone.  This
  # ensures scheduled posts align with local time for users in
  # Ukraine.
  main:
    time-zone: Europe/Kyiv

telegram:
  bots:
    carpathianBot:
      # Provide your bot credentials via environment variables or
      # override in an external config file.
      username: ${BOT_USERNAME:your-bot-username}
      token: ${BOT_TOKEN:your-bot-token}
      path: ${BOT_PATH:/}
      webhook:
        enabled: false

logging:
  level:
    # Enable SQL logging to aid debugging of queries.
    org.hibernate.SQL: debug